name: Deploy Application to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Переходим в рабочую папку проекта
            cd /opt/richart
            
            # Подтягиваем последние изменения из Git
            git pull origin main
            
            # Пересобираем и перезапускаем Docker-контейнеры в фоновом режиме
            docker compose up -d --build
            
            echo "Deployment successful! 🚀"